### PR TITLE
ADD CONTACT  SECTION 

### LINKED ISSUE #38: ADD CONTACT SECTION
**Describe the bug**
A clear and concise description of what the bug is: The README file is missing a Contact section and a Contributor section, making it difficult for users and contributors to get in touch or understand how to contribute to the project.

**To Reproduce**

1. Go to the repository's README file.
2. Scroll through the file to find the Contact and Contributor sections.
3. See error as these sections are missing.

**Expected behavior**
The README should include a Contact section to provide information on how users can reach out for support or feedback, and a Contributor section to guide potential contributors on how to get involved.

**Screenshots**
No screenshots applicable.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 96.0.4664.45

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S21
- OS: Android 12
- Browser: Chrome
- Version: 96.0

**Additional context**
Adding these sections would enhance communication and collaboration within the project, making it easier for both users and contributors to engage.

### PR DESCRIPTION
**Pull request by alo7lika**
---
name: Pull request
about: Maintain this format while making a PR
title: "Add Contact Section to README"
labels: "documentation"
assignees: "alo7lika"
---

## Description

Please include a summary of the changes and the related issue(s) if applicable. Explain the motivation behind these changes and what benefits they bring to the project.

**ADD CONTACT SECTION on README file**: This change introduces a contact section in the README, allowing users and contributors to reach out for inquiries or suggestions. This enhances communication within the community and improves user engagement.

Fixes #38  (issue)

## Type of Change

Please delete options that are not relevant:

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (changes to documentation only)
- [ ] Chore (cleanup or minor improvement that does not change functionality)

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings or errors.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if applicable)

Screenshot 2024-10-20 203014

## Additional Information

Please add any other relevant information or context for the reviewers.

This addition helps improve community involvement by providing clear contact details for project inquiries. The new contact section will be visible in the README, ensuring it's easily accessible for everyone interested in the project.

### CODE REVIEW

**Comment by alo7lika** [comment]
@Git21221  the task has been completed.

**Comment by Git21221** [comment]
@alo7lika looks good but can you make this PR to dev branch? for more info see [guide](https://github.com/Git21221/form-snippet/blob/main/CONTRIBUTING.md). main branch has some pipeline to NPM and other services.

**Comment by Git21221** [comment]
@alo7lika any update on PR?

**Comment by alo7lika** [comment]
> @alo7lika any update on PR?

Since I'm a beginner I'm facing an issue connecting it to the dev branch

**Comment by Git21221** [comment]
@alo7lika it's fine, I got it.

**Pull request merged**
